version: '3.8'

services:
  orders-db:
    container_name: orders_database
    image: postgres:14.3
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234QWER
      - POSTGRES_DB=ordersdb
